#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar  3 20:15:46 2018

@author: carsonluuu
"""

from sklearn.neural_network import MLPRegressor

import pandas as pd
import matplotlib.pyplot as plt
import math

from sklearn import preprocessing
from sklearn import cross_validation
from sklearn.metrics import mean_squared_error

data = pd.read_csv('network_backup_dataset.csv')
labels = data.columns

week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

def OneHotEncoding(label, data):
    tmpData = pd.get_dummies(data,columns=[str(label)])
    return tmpData

for i in range(5):
    data = OneHotEncoding(labels[i], data)