#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 13 16:21:13 2018

@author: carsonluuu
"""
##Load data from files
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
 
# Importing the dataset
#header = ['user_id', 'movie_id', 'rating', 'timestamp']
#dataset = pd.read_csv('ratings.csv', names=header)
#
#n_users = dataset.user_id.unique().shape[0]
#n_items = dataset.movie_id.unique().shape[0]

dataset = pd.read_csv('ratings.csv')
X = dataset.iloc[:, :-1].values
src_data = X[:,0:3]

user_total = int(max(X[:,0]))
movieID_total = int(max(X[:,1]))

R = np.empty((user_total, movieID_total))
R[:] = np.nan

for i in range(len(src_data)):
    m = int(src_data[i][0] - 1)
    n = int(src_data[i][1] - 1)
    R[m][n] = src_data[i][2]
    
#Compute the sparsity of the movie rating data
#print(1 - np.isnan(data_matrix).sum()/(user_total*movieID_total))
rates_count = []
for rate in np.arange(0, 5.5, 0.5):
    rate_count = np.count_nonzero(R == rate)
    rates_count.append(rate_count)

plt.hist(rates_count, bins=np.arange(0, 5.5, 0.5))